# Generated by Django 5.1.1 on 2024-09-09 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportcards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='grade',
        ),
        migrations.AddField(
            model_name='grade',
            name='agc_1parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='AGC 1er Parcial'),
        ),
        migrations.AddField(
            model_name='grade',
            name='aic_1parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='AIC 1er Parcial'),
        ),
        migrations.AddField(
            model_name='grade',
            name='eva_1parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='EVA 1er Parcial'),
        ),
        migrations.AddField(
            model_name='grade',
            name='lec_1parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='LEC 1er Parcial'),
        ),
        migrations.AddField(
            model_name='grade',
            name='promedio_1parcial',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Promedio 1er Parcial'),
        ),
        migrations.AddField(
            model_name='grade',
            name='tai_1parcial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='TAI 1er Parcial'),
        ),
    ]
